name: "Application CI/CD"

on:
  push:
    branches:
      - "main"

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    name: "Continuous Integration"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Log in to Docker Hub"
        uses: "docker/login-action@v3"
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"

      - name: "Build the Docker image"
        run: "docker build productivity_app -t ${{ secrets.DOCKERHUB_USERNAME }}/cn-post-1"

      - name: "Push the Image to Docker Hub"
        run: "docker push ${{ secrets.DOCKERHUB_USERNAME }}/cn-post-1"

  cd:
    name: "Continuous Deployment"
    needs: ci
    runs-on: "ubuntu-latest"

    steps:
      # Authenticate to GCP using Workload Identity Federation
      - name: "Auth in GCP"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}"
          service_account: "${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}"
          create_credentials_file: true

      - name: "Deploy to a new revision on Cloud Run"
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: "${{ env.SERVICE_ID }}"
          region: "${{ env.SERVICE_REGION }}"
          image: "${{ env.SERVICE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/dockerhub-remote-repo/${{ secrets.DOCKERHUB_USERNAME }}/cn-post-1:latest'

